### ISSUE TITLE
DGN2200v4 requests can be simpler

### ISSUE THREAD

**Issue by matteocontrini** [balloob/pynetgear#1]
I've tested the HTTP requests and I've found that the list of connected devices can be retrieved without authentication.
Just POST to `routerlogin.net:5000/soap/server_sa/` with `SOAPAction` header set to `"urn:NETGEAR-ROUTER:service:DeviceInfo:1#GetAttachDevice"` and you get the response.
Content and all the other headers seem to be optional.

**Comment by balloob** [comment]
Oh wow, that's a great improvement. Let me add this to the library.

**Comment by balloob** [comment]
Just pushed version 0.2 with your tips included d6769711f43bd4ffd61bf59cbeddef6a2ddd19b0

Host, user and pass are now all optional parameters, thanks!

**Comment by balloob** [comment]
note, this feature only works if you are using a wired connection to connect to the router.
