### ISSUE TITLE
Unexpected entry's parse errors

### ISSUE THREAD

**Issue by jmvermeulen** [balloob/pynetgear#10]
Hi,

I'm having trouble with parsing my devices.
All the devices show up like unexpected entry's:
Unexpected entry: ['XX:XX:XX:XX:XX:XX@7', '10.0.0.9', 'MY-PHONE']

So the devices can be read out, but I think some kind of parsing fails.
I'm using a WNDR3700v2 on latest original firmware.

Is there any way I can help fix this issue? For example can I get the raw response some way?

Thanks! 

Edit:
Something a device does show up, but with invalid values in mac and name:
Device(signal=None, ip='10.0.0.13', name='&lt', mac='unknown&gt', type=None, link_rate=0)

**Comment by jmvermeulen** [comment]
I think I found the problem.

A snip of the raw SOAP response:
` <NewAttachDevice>8@1;10.0.0.4;CHROMECAST;A4:77:33:E0:89:20@2;10.0.0.7;&amp;lt;unknown&amp;gt;;9C:04:EB:C3:88:96</NewAttachDevice>`

My router returns some device hostnames as <unknown>. but this value is decoded as `&amp;lt;unknown&amp;gt;`.

Since this lib splits the devices at `;` this fails.

If the hostname is xml-decoded it translates to `&lt;unknown&gt;;`.
Then html-decoded it becomes `<unknown>;`, which is valid and can safely be parsed and spitted at `;`.

Is it possible to always XML and HTML decode the response before further processing?

**Comment by balloob** [comment]
Decoding sounds like a good idea.

**Comment by matthagenbuch** [comment]
I'm having the same issue as @jmvermeulen with `<unknown>` device names.  It prevents me from using a handful of my devices for device tracking in HASS

**Comment by ArneCL** [comment]
Thanks for your input @jmvermeulen !
Please find my PR based on your comment above.
However, it seems to me that only "unknown" devices are double-escaped. Known devices are listed with their hostname (_and should therefore only contain the letters a-z & -_). Hence, I decided against double-unescaping the whole response because of this special-case.

Cheers,
Arne
