### ISSUE TITLE
ResponseCode changes in Nighthawks?

### ISSUE THREAD

**Issue by Marakai** [balloob/pynetgear#13]
I'm using your code on a Nighthawk M1. It looks like Netgear changed the < ResponseCode > from 3 to 4 digits. Otherwise SOAP requests seem to be going through. Still testing.

Also looks like the traffic meter request has changed. GetTrafficMeterStatistics/GetTrafficMeterStatisticsResponse comes back as invalid request.

**Comment by ArneCL** [comment]
@Marakai For my old WNDR3700v2 (Firmware V1.0.1.14) the ResponseCodes are still the same (eventhough it does not support the Traffic Meter feature). Unfortunately I don't own a Netgear Nighthawk - would it be possible for you (or anyone else) to provide a http-dump of the request/response from the genie-app to your router? 


For IOs devices this was very helpful:
[How To Inspect IOs http-traffic](https://www.engadget.com/2011/02/21/how-to-inspect-ioss-http-traffic-without-spending-a-dime/)

**Comment by gruijter** [comment]
just fyi: for my R7000 with V1.0.9.6_1.2.19 the ResponseCodes are 3 digits

**Comment by Marakai** [comment]
Apologies for the silence. Sadly, I didn't keep a copy of the code changes I made, as I ended up writing a whole new app to specifically monitor the Nighthawk. Using Fiddler I was able to reverse engineer a number of interesting  features to extract usage data - which is actually offered in JSON through a REST interface!

**Comment by Uninen** [comment]
I'm having a problemn connecting to my Nighthawk M1 as well. It seems it indeed returns four number response codes:

Request:
```
POST /soap/server_sa/ HTTP/1.1
Host: routerlogin.net
Pragma: no-cache
Accept: text/xml
SOAPAction: "urn:NETGEAR-ROUTER:service:ParentalControl:1#Authenticate"
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Accept-Language: en-us
Content-Type: text/xml; charset=utf-8
Content-Length: 701
User-Agent: SOAP Toolkit 3.0
Connection: close

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<SOAP-ENV:Envelope xmlns:SOAPSDK1="http://www.w3.org/2001/XMLSchema" xmlns:SOAPSDK2="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAPSDK3="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header>
<SessionID>10588AE69687E58D9A00</SessionID>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
<Authenticate>
<NewUsername xsi:type="xsd:string" xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance">admin</NewUsername>
<NewPassword xsi:type="xsd:string" xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance">password</NewPassword>
</Authenticate>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Response:
```
HTTP/1.1 200 OK
Server: httpd/2.7 (Netgear; D86)
Date: Fri, 12 Oct 2018 14:40:16 GMT
Connection: close
Content-Type: text/xml; charset="UTF-8"
Content-Length: 356

<?xml version="1.0" encoding="UTF-8" ?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <SOAP-ENV:Body> <m:AuthenticateResponse xmlns:m="urn:NETGEAR-ROUTER:service:ParentalControl:1" /> <ResponseCode>0000</ResponseCode>  </SOAP-ENV:Body> </SOAP-ENV:Envelope>
```

I've tested few different requests and it seems consistent. Also it does provide a JSON api for the web client, I might use that to get the data I need as I've been fiddling with pynetgear a couple of hours and it doesn't work with the same inputs as the genie app works. (So the data and router is working, pynetgear for some reason not.)
