### ISSUE TITLE
Improvement: Change default-port to 80

### ISSUE THREAD

**Issue by ArneCL** [balloob/pynetgear#19]
Netgear seems to have established Port 80 as default port for their Server - See also [Netgear Knowledge Base](https://kb.netgear.com/12923/Router-Initial-Setup-FAQ):

> Visit http://www.routerlogin.com. If http://www.routerlogin.com does not work, try the following:
> 
>     http://www.routerlogin.net 
>     http://192.168.1.1
>     http://192.168.0.1
>     http://10.0.0.1

**Comment by gruijter** [comment]
This is not what I am experiencing with the R7000 on firmware V1.0.9.6_1.2.19.

The SOAP interface is still at port 5000

**Comment by ArneCL** [comment]
Hm 🤔  
In #9 @davehalladay reported that he could access his Nighthawk X4 R7500v2 via port 80
In #6 @ghost reported that he could access his WNR2000v4 via port 80

Unfortunately, I don't see any consistency here and was under the impression that Netgear provides the SOAP interface through the usual HTTP Port TCP/80 😟 

Any Ideas?
-> I will leave this open so you guys can vote for/against it

**Comment by gruijter** [comment]
I think they mean that the normal interface is at port 80. That is also what the Netgear knowledge base link says. But the SOAP interface is still at 5000.

When sniffing the traffic from my Genie app, I see it immediately going to port 5000 for SOAP. But first it checks this page (no login required): http://routerlogin.net/currentsetting.htm

result for my R7000:
```Firmware=V1.0.9.6_1.2.19 RegionTag=R7000_NA Region=us Model=R7000 InternetConnectionStatus=Up ParentalControlSupported=1 SOAPVersion=3.18 ReadyShareSupportedLevel=29 XCloudSupported=1```

Maybe it checks the SOAP version or firmware level to define a port?

**Comment by ArneCL** [comment]
@gruijter 
I can confirm that the Iphone App performs a GET [http://routerlogin.net/currentsetting.htm](http://routerlogin.net/currentsetting.htm)
Output for the trusty WNR3700 (Note the missing SOAP-Version Tags):
`Firmware=V1.0.1.14GR RegionTag=WNDR3700v2_GR Region=de Model=WNDR3700v2 InternetConnectionStatus=Up ParentalControlSupported=1 `

However, the Requests are all POSTs to [http://routerlogin.net/soap/server_sa/](http://routerlogin.net/soap/server_sa/) - i.e. Port80. 

What exactly did you try to use port 80 for SOAP access ?
Are you able to connect to port 80 through pynetgear ?
I've seen that sometimes the router seems to deny any requests at all (maybe some kind of DOS protection), so maybe you give have to give it a second/third try sometimes....

**Comment by gruijter** [comment]
I tried pyNetgear and set the port to 80....
```python -m pynetgear mypassword 10.0.0.1 admin 80```

reply:
```Error communicating with the Netgear router```

**Comment by MatMaul** [comment]
Autodetection of the URL added, it will now try in this order:
http://routerlogin.net:5000
https://routerlogin.net
http://routerlogin.net

Will be available in the next release.
