### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by digdugg** [balloob/pynetgear#2]
Running this on a NetGear WNDR3700v3 and receiving the following error after specifying login details and IP address in my configuration.yaml.

```
16-01-02 02:01:48 homeassistant.components.device_tracker: Error setting up platform netgear
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/device_tracker/__init__.py", line 124, in setup_platform
    scanner = platform.get_scanner(hass, {DOMAIN: p_config})
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/device_tracker/netgear.py", line 36, in get_scanner
    scanner = NetgearDeviceScanner(host, username, password)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/device_tracker/netgear.py", line 59, in __init__
    results = self._api.get_attached_devices()
  File "/home/pi/.homeassistant/lib/pynetgear/__init__.py", line 77, in get_attached_devices
    ip, name, mac, link_type = info[1:5]
ValueError: need more than 3 values to unpack
```

I took liberty to do a print before the 3 value unpack and received the following output of the contents of info the line before the exception

```
>>> print(ng.get_attached_devices())
['12@1', '192.168.1.2', '--', '28:C6:8E:CE:9C:AB']
```

Not sure what the data should be to make a working patch here.  Let me know if I can help debug further.

**Comment by balloob** [comment]
Looks like an off by one error as the data you logged shows signal, ip, name, mac. Do you by any chance have device names that contain `@` in your network?

**Comment by digdugg** [comment]
There are no devices in my home network that have an '@' in the device name.

**Comment by digdugg** [comment]
Fix is here.

http://paste.ubuntu.com/14371023/

Tried to figure out generating a PR to make it more proper but the TLDR is sanitized more input checking length of info and if info exists.  Zero'd out link_rate variable and NULL'd link_type in my edge case.  Tested and working on latest pip3 install of homeassistant.

**Comment by balloob** [comment]
Version 0.3.1 has been published to PyPi including your fix.

**Comment by digdugg** [comment]
Did some more digging and it appears that the first entry aligns with 'wireless' or 'wired'.  Is link_type variable typically assigned to which interface the associated device is connected over, like wired/wireless?  If so I can generate a new PR assign it the correct value instead of null'ing it out.

**Comment by balloob** [comment]
I only have the R6300 to test with but I get both link type and speed. [my response](https://github.com/balloob/pynetgear/blob/master/capture/device_scan.response#L14)
