### ISSUE TITLE
Anyone any experience with pynetgear on Orbi AC3000?

### ISSUE THREAD

**Issue by gruijter** [balloob/pynetgear#23]
Hi,

I have made a nodejs based app for the Homey home automation platform. See https://apps.athom.com/app/com.gruijter.netgear

My code is loosely based on the work from pynetgear. I have made a nodejs module that can be found here: https://github.com/gruijter/netgear.js 

I have feedback that it works on R7000, R8000. But on the Orbi AC3000 it fails somehow. Does anyone have experience with the Orbi? E.g. what port is the SOAP interface port on, and does pynetgear work with the orbi? Or are there differences in SOAP commands/responses?

Thx!

**Comment by matrover** [comment]
i've used fiddler to verifiy the port that the Orbi app is using and its the same 5000 port. the netgear genie app uses port 80

**Comment by gruijter** [comment]
@matrover Do I understand correctly that the Orbi can work with the Genie app, and also with a special orbi app?

Could you post the SOAP login sequence and response when logging in to an orbi with the genie app? Thx!

**Comment by matrover** [comment]
@gruijter Yes it does, the login sequence can be found here: https://pastebin.com/kbmeEpqU

Thnx!

**Comment by MatMaul** [comment]
This lib works fine with Orbi, and now you don't need to specify anything anymore (except password) it will autodetect the URL.

**Comment by MatMaul** [comment]
This is for the next release.
