### ISSUE TITLE
Unexpected entries...

### ISSUE THREAD

**Issue by digdugg** [balloob/pynetgear#4]
16-01-12 04:48:52 pynetgear: Unexpected entry: []
16-01-12 04:49:02 pynetgear: Unexpected entry: []
16-01-12 04:49:04 pynetgear: Unexpected entry: []
16-01-12 04:49:14 pynetgear: Unexpected entry: []
16-01-12 04:49:19 pynetgear: Unexpected entry: []
16-01-12 04:49:26 pynetgear: Unexpected entry: []
16-01-12 04:49:28 pynetgear: Unexpected entry: []
16-01-12 04:49:38 pynetgear: Unexpected entry: []
16-01-12 04:49:43 pynetgear: Unexpected entry: []

Getting these in home-assistant.log when using the latest version here.  Not sure if this is on the home-assistant side or pynetgear, so opening issue here.

**Comment by balloob** [comment]
I guess we could change the logging so that when the list is empty, we will not issue any warning but if it has between 1 … 3 entries we'll log it.

**Comment by digdugg** [comment]
Fix merged, closing.
