### ISSUE TITLE
Support for WNR2000v4 / or port specification

### ISSUE THREAD

**Issue by DVDave15** [balloob/pynetgear#6]
Ok, this is not really an "issue" but perhaps it will allow pynetgear to work with the Netgear WNR2000v4 which it doesn't seem to work with.

I think NETGEAR Genie talks to the WNR2000v4 on port 5555. When I run an nmap against my WNR2000v4 I get this output:

Nmap scan report for 192.168.0.1
Host is up (0.017s latency).
Not shown: 995 closed ports
PORT      STATE SERVICE
53/tcp    open  domain
80/tcp    open  http
3333/tcp  open  dec-notes
5555/tcp  open  freeciv
49152/tcp open  unknown

When I ran NETGEAR Genie while watching in WireShark, I saw a lot of communication to port 5555 which I didn't see otherwise.

I think if the port can be specified, it may just work. If you allow that option I can give it a try and let you know.

Or if you have a better way of figuring it out, let me know, I'm happy to help.

**Comment by balloob** [comment]
pynetgear uses the Netgear SOAP api which communicates over HTTP. Port 5555
uses a freeciv protocol so this will not work.

On Sat, Mar 19, 2016 at 4:48 PM, DVDave15 <notifications@github.com> wrote:

> Ok, this is not really an "issue" but perhaps it will allow pynetgear to
> work with the Netgear WNR2000v4 which it doesn't seem to work with.
>
> I think NETGEAR Genie talks to the WNR2000v4 on port 5555. When I run an
> nmap against my WNR2000v4 I get this output:
>
> Nmap scan report for 192.168.0.1
> Host is up (0.017s latency).
> Not shown: 995 closed ports
> PORT STATE SERVICE
> 53/tcp open domain
> 80/tcp open http
> 3333/tcp open dec-notes
> 5555/tcp open freeciv
> 49152/tcp open unknown
>
> When I ran NETGEAR Genie while watching in WireShark, I saw a lot of
> communication to port 5555 which I didn't see otherwise.
>
> I think if the port can be specified, it may just work. If you allow that
> option I can give it a try and let you know.
>
> Or if you have a better way of figuring it out, let me know, I'm happy to
> help.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/balloob/pynetgear/issues/6>
>



-- 
PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.

**Comment by DVDave15** [comment]
Oh, so it uses a completely different protocol? I didn't realize freeciv was a protocol, I just thought it was an open source game from a long time ago and Netgear was using the same port it used. Sorry about that, but thanks for the response! :)

**Comment by DVDave15** [comment]
Ok, sorry to be a pest, but I am now fairly certain NETGEAR Genie is speaking SOAP on port 5555 to my WNR2000v4 as I looked through the captured content and found SOAP requests very similar to the ones you captured here: https://github.com/balloob/pynetgear/tree/master/capture.

If I have time I will see if I can download the pynetgear source and see if I can figure out if I can make it work. I don't know python, but I might be able to figure it out.

**Comment by balloob** [comment]
It looks like your nmap protocol report was off then.

You can change the port by changing this line:
https://github.com/balloob/pynetgear/blob/master/pynetgear/__init__.py#L23

On Sat, Mar 19, 2016 at 6:49 PM, DVDave15 <notifications@github.com> wrote:

> Ok, sorry to be a pest, but I am now fairly certain NETGEAR Genie is
> speaking SOAP on port 5555 to my WNR2000v4 as I looked through the captured
> content and found SOAP requests very similar to the ones you captured here:
> https://github.com/balloob/pynetgear/tree/master/capture.
>
> If I have time I will see if I can download the pynetgear source and see
> if I can figure out if I can make it work. I don't know python, but I might
> be able to figure it out.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/balloob/pynetgear/issues/6#issuecomment-198825633>
>



-- 
PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.

**Comment by DVDave15** [comment]
Yeah, I think nmap just reports port 5555 as "freeciv" as the freeciv people registered that port with the name "freeciv". Yeah, I figured that was where to make the change, I'm more concerned with getting a python environment setup and running. I should be able to figure it out. I'll post back. :) 

Thanks for putting up with me. :)

**Comment by DVDave15** [comment]
Well I'm closer... By changing to port 5555 it is connecting, but something isn't quite right because I get this response:

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>401</errorCode><errorDescription>Invalid Action</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>

Which looks like either a 401 (bad username / password) or an invalid action. I even tried this while hardwired without a username and password, but it did not work.

Looking at the request compared to what I captured in wireshark, they look very close. I even updated the SOAP_LOGIN with namespaces, but with no luck. I think the Genie uses http 1.0 and the python library uses 1.1, but I doubt that would be it...

I might try a bit more.

**Comment by DVDave15** [comment]
Ok, I tried the other open ports, and low and behold port 80 works perfect. So if we just allow specifying the port in the script, everything will work perfect. I can try to issue a pull request if you like. Let me know. But anyway, sounds like a simple and easy solution! :)

**Comment by balloob** [comment]
Awesome. Yeah a pr would be great. Just make sure the default port is the
original one

**Comment by DVDave15** [comment]
Ok, it looks like I don't have permissions (Or I haven't done the push correctly) to push my branch to origin. So, I went old school and created a patch. I hope this works for you. 

Thanks!
[pynetgear.patch.zip](https://github.com/balloob/pynetgear/files/187170/pynetgear.patch.zip)

**Comment by DVDave15** [comment]
If you like this, and want me to try to make an update to the home-assistant project to also allow specifying the port, let me know and I can try to get that done for you.

**Comment by balloob** [comment]
Applied your patch: fe8b6c78388e2dc5ae004c2160ee5253e5ae68bd Thanks!

Uploaded new version as 0.3.3 to PyPi.

For Home Assistant, press the fork button on GitHub, git clone your forked repo and you should be able to push to your repo. Then from your repo you can open a PR on GitHub to my Home Assistant repo.

**Comment by DVDave15** [comment]
Ah, yeah, I was starting to go that route after uploading the patch, but ran out of time. :-)
Thanks again!
